# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Development CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        
    - run: mkdir archives
      name: Create archives folder
      
    - run: wget -O archives.txt https://drive.google.com/u/0/uc?id=1y1EFuacVzA7VthawS9GYLZZulrcYtSPN&export=download && true || true
      working-directory: ./archives
      name: Download archives list
      
    - run: while read line; do wget -O $(echo $line | sha512sum -).zip $line; done < archives.txt && true || true
      working-directory: ./archives
      name: Download Archives
        
    - run: yarn install
      name: Install dependencies
      
    - run: yarn build
      name: Build project
    
    - run: LOCAL_ARCHIVE_DIR=./archives yarn test
      name: Run unit tests
