name: Unit tests using real archives

on: [push]

jobs:
  build:
    runs-on: ['self-hosted']

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        
        
    - run: yarn install
      name: Install dependencies
    
    - run: LOCAL_ARCHIVE_DIR=/archives npm run test
      name: Run unit tests
